<template>
  <v-app>
    <v-app-bar app prominent :src="require('../assets/bg.jpg')">
      <template v-slot:img="{ props }">
        <v-img
          v-bind="props"
          gradient="to top right, rgba(19,84,122,.5), rgba(128,208,199,.8)"
        ></v-img>
      </template>

      <v-toolbar-title>Crowd Captions</v-toolbar-title>
      <v-spacer></v-spacer>
      <v-menu left bottom>
        <template v-slot:activator="{ on, attrs }">
          <v-btn icon v-bind="attrs" v-on="on">
            <v-icon>mdi-dots-vertical</v-icon>
          </v-btn>
        </template>

        <v-list>
          <v-list-item href="https://remotelearning.auckland.ac.nz/" target="_blank"
            ><v-list-item-title>Get help</v-list-item-title></v-list-item
          >
          <v-list-item
            :href="`https://auckland.au1.qualtrics.com/jfe/form/SV_eCJsZ80IJVxD0to?upi=${user.upi}`"
            target="_blank"
            ><v-list-item-title>Give feedback</v-list-item-title></v-list-item
          >
        </v-list>
      </v-menu>
    </v-app-bar>

    <v-main>
      <v-container fluid class="text-justify">
        <div class="text-body-2 mb-4">
          Kia ora {{ user.name }}! Welcome to the summer school beta for Crowd Captions. This tool
          will let you quickly jump in and suggest changes to the captions on lecture recordings.
          Because these captions are generated by robots, they're not always perfect.
        </div>
        <v-flex justify-space-around class="mb-4 d-flex" grow>
          <v-btn color="primary" class="">View the tutorial</v-btn>
          <v-dialog v-model="dialog" width="500">
            <template v-slot:activator="{ on, attrs }">
              <v-btn color="secondary" v-bind="attrs" v-on="on" class="">Give Feedback</v-btn>
            </template>

            <iframe
              style="border: none; border-radius: 0.4em; height: 950px; width: 100%;"
              :src="
                `https://auckland.au1.qualtrics.com/jfe/form/SV_eCJsZ80IJVxD0to?upi=${user.upi}&version=${version}`
              "
            ></iframe>
          </v-dialog>
        </v-flex>
        <div class="text-body-2 mb-4">
          When you notice a mistake, suggest a change or vote on a better option. These suggestions
          will be shared with others in the class who are using this tool.
        </div>
      </v-container>
    </v-main>
    <v-footer app class="d-flex justify-space-around text--secondary text-center">
      <div>Crowd Captions v{{ version }}</div>
      <div>
        <a
          href="https://www.auckland.ac.nz/en/copyright.html"
          class="text-decoration-none"
          style="color: inherit"
          >Copyright &copy; University of Auckland {{ new Date().getFullYear() }}</a
        >
      </div>
    </v-footer>
  </v-app>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      user: {
        name: "Zac",
        upi: "zmil425"
      },
      version: process.env.PACKAGE_VERSION || "0"
    };
  }
};
</script>

<style>
html {
  width: 400px;
  height: 400px;
}
</style>
