theme: jekyll-theme-cayman
title: Crowd Captions
description: Crowd Captions is a one-stop-shop for opt-in crowdsourced student captions on Panopto.
show_downloads: true
github:
  zip_url: https://bit.ly/crowdcaptions
