theme: jekyll-theme-cayman
title: Crowd Captions
description: Crowd Captions is a one-stop-shop for allowing opt-in crowdsourced student contributions to lecture recordings.
show_downloads: true
github:
  zip_url: https://github.com/uoa-compsci399-s2-2021/crowd-captions/releases/latest